[SC-467] Update to latest xchain-helpers
marsfoundation/xchain-dsr-oracle pull request #20
Opened 2024-06-09 09:46 UTC by hexonaut

Updating to the refactored version of xchain-helpers with generic receivers. Also, some minor cleanup with naming, import ordering, etc.

2024-06-12 19:02 UTC, lucas-manuel requested changes

2024-06-12 19:02 UTC, lucas-manuel commented on test/DSROracleIntegrationArbitrumOne.t.sol
> +    }
I think we can just replace this abstract function now no?

2024-06-13 09:55 UTC, hexonaut commented on test/DSROracleIntegrationArbitrumOne.t.sol
> +    }
We can't. I get that it looks like duplicate code, but it's a different `using` at the top so the function call is actually different and specific to the domain.

2024-06-26 10:53 UTC, barrutko approved these changes, later dismissed

2024-07-02 16:03 UTC, lucas-manuel approved these changes

2024-07-02 16:04 UTC, merged